apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.24.1
          imagePullPolicy: IfNotPresent
          args: ["--config.file=/etc/prometheus/prometheus.yml","--storage.tsdb.path=/prometheus","--web.console.libraries=/usr/share/prometheus/console_libraries","--web.console.templates=/usr/share/prometheus/consoles","--web.external-url=http://localhost:9090"]
          ports:
            - containerPort: 9090
              protocol: TCP
          resources:
            requests:
              memory: 500M
              cpu: 250m
            limits:
              memory: 1000M
              cpu: 500m
          volumeMounts:
          - name: prometheus-config
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-cm
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-cm
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
    scrape_configs:
      - job_name: 'micro-integrator'
        scrape_interval: 5s
        static_configs:
          - targets: ['micro-integrator:9201']
        metrics_path: "metric-service/metrics"
      - job_name: 'jmx'
        static_configs:
          - targets:
            - jmx-exporter:5556